### ISSUE TITLE
Parametrize over `T : io::Writer`+`io::Reader`?

### ISSUE THREAD

**Issue by dpc** [nathansizemore/websocket-stream#1]
I would like to test websocket-stream with mioco, which provides a type that can read/write, but is not exactly TcpStream.

Do you see any problems with parametrization over `T : io::Writer`+`io::Reader`?

**Comment by nathansizemore** [comment]
Sorry, mis-read at first...

Internally, this uses TcpStream's RawFd to do reading/writing. I keep the TcpStream around for easy cleanup when dropped out of scope. The only consideration that needs taken is when using TcpStream combined with epoll (not sure how kqueue/Windows handles this), which I believe mio uses for Linux. When adding/modding/deleting the fd from the instance, epoll cares about the original fd, and TcpStream.clone() provides a different, but linked, fd. 
You should be OK for regular reading/writing and sys level error reporting, however you may be able to use this with easier integration: https://github.com/burrows-labs/mio-websockets

I'll also be starting websocket and ssl-websocket support in my stream collections crate over the weekend if getting lower-level more fined grained control over syscall flags peaks your interest here: https://github.com/nathansizemore/simple-stream

**Comment by dpc** [comment]
`T` would call it's `drop()` when running out of scope as well. Does this crate clone TcpStreams? I was expecting it to take TcpStream, wrap it and never needing to clone.

I'll take a look at mio-websockets, thanks.

**Comment by nathansizemore** [comment]
@dpc It took me forever, but finally got websockets into simple-stream - https://nathansizemore.github.io/simple-stream/simple_stream/frame/websocket/index.html

**Comment by dpc** [comment]
Thanks! I'll try it at some point.
