### ISSUE TITLE
can this be made compatible with runtime::net::TcpStream

### ISSUE THREAD

**Issue by Gozala** [nathansizemore/websocket-stream#2]
I would like to use this with [rust runtime](https://blog.yoshuawuyts.com/runtime/) is there a way to make this compatible with it without having to rewrite the whole thing ?

**Comment by nathansizemore** [comment]
This is super old, and I don't maintain it anymore. Under the hood, it uses whatever std::net uses for it's non-blocking stuff (assuming you want non-blocking because that post is about async stuff). There's nothing special stopping it from being integrated in anything, you'll just have to know how the std lib integrates with your network stack.

**Comment by Gozala** [comment]
> This is super old, and I don't maintain it anymore. 

Does that imply it's best to avoid this ?

> Under the hood, it uses whatever std::net uses for it's non-blocking stuff (assuming you want non-blocking because that post is about async stuff). There's nothing special stopping it from being integrated in anything, you'll just have to know how the std lib integrates with your network stack.

I'm just starting with Rust so it very much could be that I'm not seeing something obvious. From what it appears `runtime::net::TcpStream` is incompatible with `std::net::TcpStream` there for I could not get it to work.

That being said I've started trying to modifying your code base to try and make it compatible with `runtime::net::TcpStream`, I hope I'll learn things along the way.

**Comment by nathansizemore** [comment]
For your use case, I'd recommend https://github.com/nathansizemore/simple-stream

It works off traits, so as long what you give it something that implements X trait, it doesn't care if it is from `std::net`, or `some::cool::lib`. 

I'm not versed in `runtime::net::TcpStream`, but I'll check it out this weekend. I'm curious on to what it offers over setting std::net socket to non-blocking.

**Comment by Gozala** [comment]
Thanks!

Here is the intro to post for runtime https://blog.yoshuawuyts.com/runtime/
